server {
    listen 3000;
    server_name localhost;

    # Путь к вашим фронтенд файлам
    root /usr/share/nginx/html/public;
    index index.html;

    # Если вы хотите напрямую раздавать src (например для js-модулей)
    location /src/ {
        alias /usr/share/nginx/html/src/;
    }

    # SPA: все маршруты отдаём index.html
    location / {
        try_files $uri /index.html;
    }
}