location /src/ {
    alias /usr/share/nginx/html/src/;
}
server {
    listen 3000;

    server_name localhost;

    root /usr/share/nginx/html/public;

    index index.html;

    # SPA fallback
    location / {
        try_files $uri /index.html;
    }

    # Проксирование API на backend
    location /api/ {
        proxy_pass http://backend:4000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Кэш для PWA файлов
    location ~* /(manifest.json|service-worker.js)$ {
        add_header Cache-Control "no-cache";
    }

    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|json)$ {
        expires 1y;
        add_header Cache-Control "public";
    }
}